language: python

matrix:
  include:
    - python: 3.6
    # - python: 3.7 Travis does not allow python 3.7 installation at present

install:
  - pip install -r requirements.txt

script:
  - pytest

branches:
  - only:
    - master
